"""setting intial value for counter

Revision ID: 123417f62c4a
Revises: 80d072699cdc
Create Date: 2025-02-13 16:12:14.148747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123417f62c4a'
down_revision: Union[str, None] = '80d072699cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO otp (counter) values (0)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
