"""counter based otp fields added to user table

Revision ID: 63eca535177c
Revises: 8bf335416c1c
Create Date: 2025-02-13 15:40:51.283597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63eca535177c'
down_revision: Union[str, None] = '8bf335416c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_counter')
    # ### end Alembic commands ###
