"""user otp counter colume removed

Revision ID: 80d072699cdc
Revises: 9498ba23054c
Create Date: 2025-02-13 15:49:17.220854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80d072699cdc'
down_revision: Union[str, None] = '9498ba23054c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_counter', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
